yaml

diff --git a/.github/workflows/run-tests.yaml b/.github/workflows/run-tests.yaml
--- a/.github/workflows/run-tests.yaml
+++ b/.github/workflows/run-tests.yaml
@@ -12,7 +12,7 @@ jobs:
         uses: actions/checkout@v2
       - name: Verify Docker Compose Installation
         run: |
-        docker-compose --version || echo "docker-compose not found"
+          docker-compose --version || echo "docker-compose not found"
       - name: Run Tests
         run: |
           make ci
