test docker-compose version

diff --git a/.github/workflows/run-tests.yaml b/.github/workflows/run-tests.yaml
--- a/.github/workflows/run-tests.yaml
+++ b/.github/workflows/run-tests.yaml
@@ -10,6 +10,9 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
+      - name: Verify Docker Compose Installation
+        run: |
+        docker-compose --version || echo "docker-compose not found"
       - name: Run Tests
         run: |
           make ci
